import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Mountain, ShieldCheck, Waves } from "lucide-react";
import { Button } from "@/components/ui/button";
import lc300HeroAsset from "@/assets/lc300-hero.jpg.asset.json";
const lc300Hero = lc300HeroAsset.url;

const TITLE = "Toyota Land Cruiser 300 | MOENCO Ethiopia";
const DESCRIPTION = "Explore the Toyota Land Cruiser 300: twin-turbo V6 power, 10-speed automatic transmission and 235 mm ground clearance.";

export const Route = createFileRoute("/toyota/land-cruiser-300")({head:()=>({meta:[{title:TITLE},{name:"description",content:DESCRIPTION},{property:"og:title",content:TITLE},{property:"og:description",content:DESCRIPTION},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:LandCruiserPage});

function LandCruiserPage(){return <div className="bg-[#0a0b0c] text-foreground"><section className="relative min-h-[780px] overflow-hidden"><img src={lc300Hero} alt="Toyota Land Cruiser 300 on rugged Ethiopian highland terrain" width={1600} height={1000} className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-[#0a0b0c] via-[#0a0b0c]/25 to-[#0a0b0c]/20"/><div className="relative mx-auto flex min-h-[780px] max-w-7xl items-end px-5 pb-16 pt-36 lg:px-8"><div><p className="text-xs font-bold uppercase tracking-[.3em] text-silver">Land Cruiser 300</p><h1 className="mt-4 max-w-4xl text-5xl font-black uppercase leading-[.88] sm:text-8xl">Master every<br/>horizon.</h1><p className="mt-6 max-w-xl text-base leading-relaxed text-foreground/70">A lighter, stronger frame. Twin-turbo V6 force. The composure to cross remote terrain and arrive with flagship comfort intact.</p><Button asChild size="lg" className="mt-8 rounded-none"><Link to="/contact">Request a private viewing <ArrowRight className="ml-2 h-4 w-4"/></Link></Button></div></div></section><section className="border-y border-silver/20"><div className="mx-auto grid max-w-7xl sm:grid-cols-3">{[["6-cylinder","Twin-turbo V6"],["10-speed","Automatic transmission"],["235 mm","Ground clearance"]].map(x=><div key={x[0]} className="border-r border-border p-8"><span className="text-3xl font-black">{x[0]}</span><span className="mt-2 block text-xs uppercase tracking-[.18em] text-muted-foreground">{x[1]}</span></div>)}</div></section><section className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="grid gap-8 lg:grid-cols-3">{[{i:Mountain,t:"Multi-Terrain Select",d:"Drive modes coordinate throttle, braking and traction for rock, sand, mud and loose surfaces."},{i:Waves,t:"Confident wading",d:"Engine-bay packaging and body sealing support difficult crossings when conditions demand it."},{i:ShieldCheck,t:"Safety Sense",d:"Driver assistance monitors the road while the full-time four-wheel-drive system manages the ground."}].map(x=><article key={x.t} className="border-t border-silver/40 py-8"><x.i className="h-6 w-6 text-silver"/><h2 className="mt-14 text-2xl font-black">{x.t}</h2><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{x.d}</p></article>)}</div></section></div>}